<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Z5X-HYD-LT010" ignored="16" name="ExistingUser" tests="16" failures="16" timestamp="2020-08-02T04:22:59 IST" time="2.667" errors="0">
  <testcase name="GET_getProfile" time="1.605" classname="com.User.GetProfile">
    <failure type="java.lang.AssertionError" message="Getting status code 403 instead of expected status code 200 expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: Getting status code 403 instead of expected status code 200 expected [200] but found [403]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- GET_getProfile -->
  <testcase name="PUT_UpdatePreferencee" time="0.274" classname="com.User.UpdatePreferences">
    <failure type="java.lang.AssertionError" message="Getting status code 403 instead of expected status code 200 expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: Getting status code 403 instead of expected status code 200 expected [200] but found [403]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- PUT_UpdatePreferencee -->
  <testcase name="GET_OtherUserProfile" time="0.03" classname="com.User.GetOtherUserProfile">
    <failure type="java.lang.AssertionError" message="Getting status code 403 instead of expected status code 200 expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: Getting status code 403 instead of expected status code 200 expected [200] but found [403]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- GET_OtherUserProfile -->
  <testcase name="PUT_UpdateProfile" time="0.026" classname="com.User.UpdateProfile">
    <failure type="java.lang.AssertionError" message="Getting status code 403 instead of expected status code 200 expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: Getting status code 403 instead of expected status code 200 expected [200] but found [403]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- PUT_UpdateProfile -->
  <testcase name="POST_DeleteBankDetails" time="0.037" classname="com.User.DeleteBankDetails">
    <failure type="java.lang.AssertionError" message="Getting status code 403 instead of expected status code 200 expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: Getting status code 403 instead of expected status code 200 expected [200] but found [403]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- POST_DeleteBankDetails -->
  <testcase name="PUT_UpdateUpiDetails" time="0.043" classname="com.User.UpdateUpiDetails">
    <failure type="java.lang.AssertionError" message="Getting status code 403 instead of expected status code 200 expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: Getting status code 403 instead of expected status code 200 expected [200] but found [403]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- PUT_UpdateUpiDetails -->
  <testcase name="POST_verifyOTP" time="0.029" classname="com.User.VerifyOTP">
    <failure type="java.lang.AssertionError" message="Getting status code 403 instead of expected status code 200 expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: Getting status code 403 instead of expected status code 200 expected [200] but found [403]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- POST_verifyOTP -->
  <testcase name="POST_DeleteUpiDetails" time="0.018" classname="com.User.DeleteUpiDetails">
    <failure type="java.lang.AssertionError" message="Getting status code 403 instead of expected status code 200 expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: Getting status code 403 instead of expected status code 200 expected [200] but found [403]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- POST_DeleteUpiDetails -->
  <testcase name="GET_GetPreferencee" time="0.016" classname="com.User.GetPreferences">
    <failure type="java.lang.AssertionError" message="Getting status code 403 instead of expected status code 200 expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: Getting status code 403 instead of expected status code 200 expected [200] but found [403]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- GET_GetPreferencee -->
  <testcase name="PUT_UpdateBankDetails" time="0.025" classname="com.User.UpdateBankDetails">
    <failure type="java.lang.AssertionError" message="Getting status code 403 instead of expected status code 200 expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: Getting status code 403 instead of expected status code 200 expected [200] but found [403]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- PUT_UpdateBankDetails -->
  <testcase name="POST_FollowUser" time="0.014" classname="com.User.FollowUser">
    <failure type="java.lang.AssertionError" message="Getting status code 403 instead of expected status code 200 expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: Getting status code 403 instead of expected status code 200 expected [200] but found [403]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- POST_FollowUser -->
  <testcase name="GET_BankDetails" time="0.036" classname="com.User.GetBankDetails">
    <failure type="java.lang.AssertionError" message="Getting status code 403 instead of expected status code 200 expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: Getting status code 403 instead of expected status code 200 expected [200] but found [403]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- GET_BankDetails -->
  <testcase name="GET_UsersFollowingMe" time="0.011" classname="com.User.GetUsersFollowingMe">
    <failure type="java.lang.IllegalArgumentException" message="path cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: path cannot be null
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- GET_UsersFollowingMe -->
  <testcase name="POST_CreateAUser" time="0.132" classname="com.User.UserLoginTest">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at java.util.ArrayList.forEach(Unknown Source)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at com.SaveResponseData.CaptureResponseNodeValue.saveIntegerNodeValue(CaptureResponseNodeValue.java:22)
at com.User.UserLoginTest.POST_CreateAUser(UserLoginTest.java:36)
... 22 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- POST_CreateAUser -->
  <testcase name="PUT_UpdateProfileImage" time="0.115" classname="com.User.UpdateProfileImage">
    <failure type="java.lang.AssertionError" message="Getting status code 403 instead of expected status code 200 expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: Getting status code 403 instead of expected status code 200 expected [200] but found [403]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- PUT_UpdateProfileImage -->
  <testcase name="POST_UnfollowUser" time="0.021" classname="com.User.UnfollowUser">
    <failure type="java.lang.AssertionError" message="Getting status code 403 instead of expected status code 200 expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: Getting status code 403 instead of expected status code 200 expected [200] but found [403]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- POST_UnfollowUser -->
  <testcase name="POST_verifyOTP" time="0.0" classname="com.User.UserApiTests">
    <ignored/>
  </testcase> <!-- POST_verifyOTP -->
  <testcase name="POST_FollowUser" time="0.0" classname="com.User.UserApiTests">
    <ignored/>
  </testcase> <!-- POST_FollowUser -->
  <testcase name="POST_DeleteUpiDetails" time="0.0" classname="com.User.UserApiTests">
    <ignored/>
  </testcase> <!-- POST_DeleteUpiDetails -->
  <testcase name="GET_UsersFollowingMe" time="0.0" classname="com.User.UserApiTests">
    <ignored/>
  </testcase> <!-- GET_UsersFollowingMe -->
  <testcase name="PUT_UpdateProfileImage" time="0.0" classname="com.User.UserApiTests">
    <ignored/>
  </testcase> <!-- PUT_UpdateProfileImage -->
  <testcase name="GET_BankDetails" time="0.0" classname="com.User.UserApiTests">
    <ignored/>
  </testcase> <!-- GET_BankDetails -->
  <testcase name="PUT_UpdateUpiDetails" time="0.0" classname="com.User.UserApiTests">
    <ignored/>
  </testcase> <!-- PUT_UpdateUpiDetails -->
  <testcase name="POST_CreateAUser" time="0.0" classname="com.User.UserApiTests">
    <ignored/>
  </testcase> <!-- POST_CreateAUser -->
  <testcase name="PUT_UpdatePreferencee" time="0.0" classname="com.User.UserApiTests">
    <ignored/>
  </testcase> <!-- PUT_UpdatePreferencee -->
  <testcase name="POST_DeleteBankDetails" time="0.0" classname="com.User.UserApiTests">
    <ignored/>
  </testcase> <!-- POST_DeleteBankDetails -->
  <testcase name="PUT_UpdateBankDetails" time="0.0" classname="com.User.UserApiTests">
    <ignored/>
  </testcase> <!-- PUT_UpdateBankDetails -->
  <testcase name="GET_OtherUserProfile" time="0.0" classname="com.User.UserApiTests">
    <ignored/>
  </testcase> <!-- GET_OtherUserProfile -->
  <testcase name="GET_GetPreferencee" time="0.0" classname="com.User.UserApiTests">
    <ignored/>
  </testcase> <!-- GET_GetPreferencee -->
  <testcase name="PUT_UpdateProfile" time="0.0" classname="com.User.UserApiTests">
    <ignored/>
  </testcase> <!-- PUT_UpdateProfile -->
  <testcase name="POST_UnfollowUser" time="0.0" classname="com.User.UserApiTests">
    <ignored/>
  </testcase> <!-- POST_UnfollowUser -->
  <testcase name="GET_getProfile" time="0.0" classname="com.User.UserApiTests">
    <ignored/>
  </testcase> <!-- GET_getProfile -->
</testsuite> <!-- ExistingUser -->
