<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" ignored="0" total="32" passed="26">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11624" started-at="2020-08-06T11:51:12 IST" finished-at="2020-08-06T11:51:23 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11624" started-at="2020-08-06T11:51:12 IST" finished-at="2020-08-06T11:51:23 IST">
      <class name="com.User.UserApiTests">
        <test-method status="PASS" signature="def_baseUrl()[pri:0, instance:com.User.UserApiTests@56235b8e]" name="def_baseUrl" is-config="true" duration-ms="548" started-at="2020-08-06T11:51:11 IST" finished-at="2020-08-06T11:51:12 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- def_baseUrl -->
        <test-method status="PASS" signature="POST_CreateAUser_Nodes()[pri:0, instance:com.User.UserApiTests@56235b8e]" name="POST_CreateAUser_Nodes" duration-ms="3774" started-at="2020-08-06T11:51:12 IST" description="Verify createUser API Nodes" finished-at="2020-08-06T11:51:16 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- POST_CreateAUser_Nodes -->
        <test-method status="FAIL" signature="POST_CreateAUser_StatusCode_Time()[pri:0, instance:com.User.UserApiTests@56235b8e]" name="POST_CreateAUser_StatusCode_Time" duration-ms="814" started-at="2020-08-06T11:51:16 IST" description="Verify createUser API StatusCode, ResponseTime" finished-at="2020-08-06T11:51:17 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Time allocated 765ms is greater than expected time 500ms expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Time allocated 765ms is greater than expected time 500ms expected [true] but found [false]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:66)
at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:651)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- POST_CreateAUser_StatusCode_Time -->
        <test-method status="FAIL" signature="POST_verifyOTP_Nodes()[pri:1, instance:com.User.UserApiTests@56235b8e]" name="POST_verifyOTP_Nodes" duration-ms="286" started-at="2020-08-06T11:51:17 IST" description="Verify userName&amp;OTP API Nodes" finished-at="2020-08-06T11:51:17 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"is_guest" node is not present in the response body expected [true] but found [false],
"full_name" node is not present in the response body expected [true] but found [false],
"dob" node is not present in the response body expected [true] but found [false],
"email" node is not present in the response body expected [true] but found [false],
"gender" node is not present in the response body expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"is_guest" node is not present in the response body expected [true] but found [false],
"full_name" node is not present in the response body expected [true] but found [false],
"dob" node is not present in the response body expected [true] but found [false],
"email" node is not present in the response body expected [true] but found [false],
"gender" node is not present in the response body expected [true] but found [false]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:66)
at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:651)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- POST_verifyOTP_Nodes -->
        <test-method status="PASS" signature="POST_verifyOTP_StatusCode_Time()[pri:1, instance:com.User.UserApiTests@56235b8e]" name="POST_verifyOTP_StatusCode_Time" duration-ms="285" started-at="2020-08-06T11:51:17 IST" description="Verify userName&amp;OTP API Response Code, ResponseTime" finished-at="2020-08-06T11:51:17 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- POST_verifyOTP_StatusCode_Time -->
        <test-method status="PASS" signature="GET_GetPreference_Nodes()[pri:2, instance:com.User.UserApiTests@56235b8e]" name="GET_GetPreference_Nodes" duration-ms="176" started-at="2020-08-06T11:51:17 IST" description="Verify getPreference API Nodes" finished-at="2020-08-06T11:51:17 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GET_GetPreference_Nodes -->
        <test-method status="PASS" signature="GET_GetPreference_StatusCode_Time()[pri:2, instance:com.User.UserApiTests@56235b8e]" name="GET_GetPreference_StatusCode_Time" duration-ms="185" started-at="2020-08-06T11:51:17 IST" description="Verify getPreference API StatusCode, Response Time" finished-at="2020-08-06T11:51:17 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GET_GetPreference_StatusCode_Time -->
        <test-method status="PASS" signature="GET_OtherUserProfile_Nodes()[pri:2, instance:com.User.UserApiTests@56235b8e]" name="GET_OtherUserProfile_Nodes" duration-ms="298" started-at="2020-08-06T11:51:17 IST" description="Verify getOtherUserProfile API Nodes" finished-at="2020-08-06T11:51:18 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GET_OtherUserProfile_Nodes -->
        <test-method status="PASS" signature="GET_OtherUserProfile_StatusCode_Time()[pri:2, instance:com.User.UserApiTests@56235b8e]" name="GET_OtherUserProfile_StatusCode_Time" duration-ms="348" started-at="2020-08-06T11:51:18 IST" description="Verify getOtherUserProfile API StatusCode, Response Time" finished-at="2020-08-06T11:51:18 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GET_OtherUserProfile_StatusCode_Time -->
        <test-method status="PASS" signature="GET_UsersFollowingMe()[pri:2, instance:com.User.UserApiTests@56235b8e]" name="GET_UsersFollowingMe" duration-ms="246" started-at="2020-08-06T11:51:18 IST" description="Verify UsersFollowingMe API Nodes " finished-at="2020-08-06T11:51:18 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GET_UsersFollowingMe -->
        <test-method status="PASS" signature="GET_UsersFollowingMe_StatusCode_Time()[pri:2, instance:com.User.UserApiTests@56235b8e]" name="GET_UsersFollowingMe_StatusCode_Time" duration-ms="222" started-at="2020-08-06T11:51:18 IST" description="Verify UsersFollowingMe API StatusCode, Response Time" finished-at="2020-08-06T11:51:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GET_UsersFollowingMe_StatusCode_Time -->
        <test-method status="PASS" signature="GET_getProfile_Nodes()[pri:2, instance:com.User.UserApiTests@56235b8e]" name="GET_getProfile_Nodes" duration-ms="281" started-at="2020-08-06T11:51:19 IST" description="Verify getProfile API Nodes" finished-at="2020-08-06T11:51:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GET_getProfile_Nodes -->
        <test-method status="PASS" signature="GET_getProfile_StatusCode_Time()[pri:2, instance:com.User.UserApiTests@56235b8e]" name="GET_getProfile_StatusCode_Time" duration-ms="296" started-at="2020-08-06T11:51:19 IST" description="Verify getProfile API StatusCode, Response Time" finished-at="2020-08-06T11:51:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GET_getProfile_StatusCode_Time -->
        <test-method status="PASS" signature="PUT_UpdateBankDetails_Nodes()[pri:2, instance:com.User.UserApiTests@56235b8e]" name="PUT_UpdateBankDetails_Nodes" duration-ms="193" started-at="2020-08-06T11:51:19 IST" description="Verify UpdateBankDetails API Nodes" finished-at="2020-08-06T11:51:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PUT_UpdateBankDetails_Nodes -->
        <test-method status="PASS" signature="PUT_UpdateBankDetails_StatusCode_Time()[pri:2, instance:com.User.UserApiTests@56235b8e]" name="PUT_UpdateBankDetails_StatusCode_Time" duration-ms="160" started-at="2020-08-06T11:51:19 IST" description="Verify UpdateBankDetails API StatusCode, Response Time" finished-at="2020-08-06T11:51:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PUT_UpdateBankDetails_StatusCode_Time -->
        <test-method status="PASS" signature="PUT_UpdatePreference_Nodes()[pri:2, instance:com.User.UserApiTests@56235b8e]" name="PUT_UpdatePreference_Nodes" duration-ms="163" started-at="2020-08-06T11:51:19 IST" description="Verify updatePreference API Nodes" finished-at="2020-08-06T11:51:20 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PUT_UpdatePreference_Nodes -->
        <test-method status="PASS" signature="PUT_UpdatePreferences_StatusCode_Time()[pri:2, instance:com.User.UserApiTests@56235b8e]" name="PUT_UpdatePreferences_StatusCode_Time" duration-ms="212" started-at="2020-08-06T11:51:20 IST" description="Verify updatePreference API StatusCode, Response Time" finished-at="2020-08-06T11:51:20 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PUT_UpdatePreferences_StatusCode_Time -->
        <test-method status="PASS" signature="PUT_UpdateProfileImage_Nodes()[pri:2, instance:com.User.UserApiTests@56235b8e]" name="PUT_UpdateProfileImage_Nodes" duration-ms="342" started-at="2020-08-06T11:51:20 IST" description="Verify updateProfileImage API Nodes" finished-at="2020-08-06T11:51:20 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PUT_UpdateProfileImage_Nodes -->
        <test-method status="PASS" signature="PUT_UpdateProfileImage_StatusCode_Time()[pri:2, instance:com.User.UserApiTests@56235b8e]" name="PUT_UpdateProfileImage_StatusCode_Time" duration-ms="243" started-at="2020-08-06T11:51:20 IST" description="Verify updateProfileImage API StatusCode, Response Time" finished-at="2020-08-06T11:51:20 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PUT_UpdateProfileImage_StatusCode_Time -->
        <test-method status="FAIL" signature="PUT_UpdateProfile_Nodes()[pri:2, instance:com.User.UserApiTests@56235b8e]" name="PUT_UpdateProfile_Nodes" duration-ms="206" started-at="2020-08-06T11:51:20 IST" description="Verify updateProfile API Nodes" finished-at="2020-08-06T11:51:21 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"profile_picture" node is not present in the response body expected [true] but found [false],
"under18" node is not present in the response body expected [true] but found [false],
"is_guest" node is not present in the response body expected [true] but found [false],
"bank_details" node is not present in the response body expected [true] but found [false],
"@type" node is not present in the response body expected [true] but found [false],
"bank_account_full_name" node is not present in the response body expected [true] but found [false],
"accountType" node is not present in the response body expected [true] but found [false],
"accountNumber" node is not present in the response body expected [true] but found [false],
"ifscCode" node is not present in the response body expected [true] but found [false],
"mobile" node is not present in the response body expected [true] but found [false],
"created_at" node is not present in the response body expected [true] but found [false],
"upi_details" node is not present in the response body expected [true] but found [false],
"@type" node is not present in the response body expected [true] but found [false],
"upi" node is not present in the response body expected [true] but found [false],
"user_id" node is not present in the response body expected [true] but found [false],
"username" node is not present in the response body expected [true] but found [false],
"display_language" node is not present in the response body expected [true] but found [false],
"full_name" node is not present in the response body expected [true] but found [false],
"dob" node is not present in the response body expected [true] but found [false],
"email" node is not present in the response body expected [true] but found [false],
"gender" node is not present in the response body expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"profile_picture" node is not present in the response body expected [true] but found [false],
"under18" node is not present in the response body expected [true] but found [false],
"is_guest" node is not present in the response body expected [true] but found [false],
"bank_details" node is not present in the response body expected [true] but found [false],
"@type" node is not present in the response body expected [true] but found [false],
"bank_account_full_name" node is not present in the response body expected [true] but found [false],
"accountType" node is not present in the response body expected [true] but found [false],
"accountNumber" node is not present in the response body expected [true] but found [false],
"ifscCode" node is not present in the response body expected [true] but found [false],
"mobile" node is not present in the response body expected [true] but found [false],
"created_at" node is not present in the response body expected [true] but found [false],
"upi_details" node is not present in the response body expected [true] but found [false],
"@type" node is not present in the response body expected [true] but found [false],
"upi" node is not present in the response body expected [true] but found [false],
"user_id" node is not present in the response body expected [true] but found [false],
"username" node is not present in the response body expected [true] but found [false],
"display_language" node is not present in the response body expected [true] but found [false],
"full_name" node is not present in the response body expected [true] but found [false],
"dob" node is not present in the response body expected [true] but found [false],
"email" node is not present in the response body expected [true] but found [false],
"gender" node is not present in the response body expected [true] but found [false]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:66)
at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:651)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PUT_UpdateProfile_Nodes -->
        <test-method status="PASS" signature="PUT_UpdateProfile_StatusCode_Time()[pri:2, instance:com.User.UserApiTests@56235b8e]" name="PUT_UpdateProfile_StatusCode_Time" duration-ms="220" started-at="2020-08-06T11:51:21 IST" description="Verify updateProfile API StatusCode, Response Time" finished-at="2020-08-06T11:51:21 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PUT_UpdateProfile_StatusCode_Time -->
        <test-method status="FAIL" signature="PUT_UpdateUpiDetails_Nodes()[pri:2, instance:com.User.UserApiTests@56235b8e]" name="PUT_UpdateUpiDetails_Nodes" duration-ms="215" started-at="2020-08-06T11:51:21 IST" description="Verify UpdateUpiDetails API Nodes" finished-at="2020-08-06T11:51:21 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"upi_details" node is not present in the response body expected [true] but found [false],
"upi" node is not present in the response body expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"upi_details" node is not present in the response body expected [true] but found [false],
"upi" node is not present in the response body expected [true] but found [false]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:66)
at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:651)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PUT_UpdateUpiDetails_Nodes -->
        <test-method status="PASS" signature="PUT_UpdateUpiDetails_StatusCode_Time()[pri:2, instance:com.User.UserApiTests@56235b8e]" name="PUT_UpdateUpiDetails_StatusCode_Time" duration-ms="186" started-at="2020-08-06T11:51:21 IST" description="Verify UpdateUpiDetails API StatusCode, Response Time" finished-at="2020-08-06T11:51:21 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PUT_UpdateUpiDetails_StatusCode_Time -->
        <test-method status="FAIL" signature="GET_BankDetails_Nodes()[pri:3, instance:com.User.UserApiTests@56235b8e]" name="GET_BankDetails_Nodes" duration-ms="223" started-at="2020-08-06T11:51:21 IST" description="Verify GetBankDetails API Nodes" finished-at="2020-08-06T11:51:22 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"bank_account_full_name" node is not present in the response body expected [true] but found [false],
"accountNumber" node is not present in the response body expected [true] but found [false],
ifscCode node is not present in the response body expected [true] but found [false],
accountType node is not present in the response body expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"bank_account_full_name" node is not present in the response body expected [true] but found [false],
"accountNumber" node is not present in the response body expected [true] but found [false],
ifscCode node is not present in the response body expected [true] but found [false],
accountType node is not present in the response body expected [true] but found [false]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:66)
at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:651)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GET_BankDetails_Nodes -->
        <test-method status="PASS" signature="GET_BankDetails_StatusCode_Time()[pri:3, instance:com.User.UserApiTests@56235b8e]" name="GET_BankDetails_StatusCode_Time" duration-ms="167" started-at="2020-08-06T11:51:22 IST" description="Verify GetBankDetails API StatusCode, Response Time" finished-at="2020-08-06T11:51:22 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GET_BankDetails_StatusCode_Time -->
        <test-method status="FAIL" signature="POST_DeleteBankDetails_Nodes()[pri:4, instance:com.User.UserApiTests@56235b8e]" name="POST_DeleteBankDetails_Nodes" duration-ms="207" started-at="2020-08-06T11:51:22 IST" description="Verify DeleteBankDetails API Nodes" finished-at="2020-08-06T11:51:22 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
"@type" node is not present in the response body expected [true] but found [false],
"@type" node is not present in the response body expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
"@type" node is not present in the response body expected [true] but found [false],
"@type" node is not present in the response body expected [true] but found [false]
at com.Reports.ReportListner.onTestFailure(ReportListner.java:65)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:66)
at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:651)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- POST_DeleteBankDetails_Nodes -->
        <test-method status="PASS" signature="POST_DeleteBankDetails_StatusCode_Time()[pri:4, instance:com.User.UserApiTests@56235b8e]" name="POST_DeleteBankDetails_StatusCode_Time" duration-ms="215" started-at="2020-08-06T11:51:22 IST" description="Verify DeleteBankDetails API StatusCode, Response Time" finished-at="2020-08-06T11:51:22 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- POST_DeleteBankDetails_StatusCode_Time -->
        <test-method status="PASS" signature="POST_DeleteUpiDetails_Nodes()[pri:5, instance:com.User.UserApiTests@56235b8e]" name="POST_DeleteUpiDetails_Nodes" duration-ms="173" started-at="2020-08-06T11:51:22 IST" description="Verify DeleteUpiDetails API Nodes" finished-at="2020-08-06T11:51:22 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- POST_DeleteUpiDetails_Nodes -->
        <test-method status="PASS" signature="POST_DeleteUpiDetails_StatusCode_Time()[pri:5, instance:com.User.UserApiTests@56235b8e]" name="POST_DeleteUpiDetails_StatusCode_Time" duration-ms="288" started-at="2020-08-06T11:51:22 IST" description="Verify DeleteUpiDetails API StatusCode, Response Time" finished-at="2020-08-06T11:51:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- POST_DeleteUpiDetails_StatusCode_Time -->
        <test-method status="PASS" signature="POST_UnfollowUser_Nodes()[pri:5, instance:com.User.UserApiTests@56235b8e]" name="POST_UnfollowUser_Nodes" duration-ms="177" started-at="2020-08-06T11:51:23 IST" description="Verify UnfollowUser API Nodes" finished-at="2020-08-06T11:51:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- POST_UnfollowUser_Nodes -->
        <test-method status="PASS" signature="POST_UnfollowUser_StatusCode_Time()[pri:5, instance:com.User.UserApiTests@56235b8e]" name="POST_UnfollowUser_StatusCode_Time" duration-ms="171" started-at="2020-08-06T11:51:23 IST" description="Verify UnfollowUser API StatusCode, Response Time" finished-at="2020-08-06T11:51:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- POST_UnfollowUser_StatusCode_Time -->
        <test-method status="PASS" signature="POST_FollowUser_Nodes()[pri:6, instance:com.User.UserApiTests@56235b8e]" name="POST_FollowUser_Nodes" duration-ms="183" started-at="2020-08-06T11:51:23 IST" description="Verify FollowUser API Nodes" finished-at="2020-08-06T11:51:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- POST_FollowUser_Nodes -->
        <test-method status="PASS" signature="POST_FollowUser_StatusCode_time()[pri:6, instance:com.User.UserApiTests@56235b8e]" name="POST_FollowUser_StatusCode_time" duration-ms="227" started-at="2020-08-06T11:51:23 IST" description="Verify FollowUser API StatusCode, Response Time" finished-at="2020-08-06T11:51:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- POST_FollowUser_StatusCode_time -->
        <test-method status="PASS" signature="SM()[pri:0, instance:com.User.UserApiTests@56235b8e]" name="SM" is-config="true" duration-ms="4899" started-at="2020-08-06T11:51:24 IST" finished-at="2020-08-06T11:51:29 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SM -->
      </class> <!-- com.User.UserApiTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
